plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

use_math: true # true to enable math support

include:
  - CREATING_STC_ACCOUNT.md
  - README.md
  - USING_LOCAL_MODEL_MATLAB.md
  - USING_LOCAL_MODEL_PYTHON.md
  - USING_STC.md